---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-invenio-app-user
  namespace: database
spec:
  encryptedData:
    password: AgCErFjHisI0szoBYR/ZSQfWylMV2O5Aw5+JaZobDdBTb2FCJvWkrL5Vx/avffDsJjrm17yzi4lG5vOT52hgOLQO7XaW8kjK9LCTwl3m0MTTsD++f8kpz83yQXfW2wr64Mymqs39UoZPq7/sb2864+uaSmv6d73wLxx3Q7HkflnB0ShuxdvFk8WlTagX8MJMTnlMxHGwSmdNrMXf7WpOBf9tF0ilRgqYvUaX7aVk4Ik32pnLH+KqhEJPitk8jxHBC+BbEbjEXHdae6hFlJ1iBpBpKzw4LcTFnORDdxCcGIPUBUDw2+uFYQ230MfmheeS2n9BHi9FNWxwrTXVeavj54B0RBUIprW0jf2GirrOKvyIcx9duv8ouPkOmlutKYY8FxXcD2Md5y9eA0oqKAWg2ZJOjieJpW41fct7rMaVGKExZT6rUg04miPNvLsyLq97kXR/ovsppfpHEtmGPiQlSFOe4KdeQotIRg0xvmVAoBoU1xNzjDbiKjRIgmK+y2yni9Lc010nJvLi008H7vpuUBfZoPBmQb1zxWGDYNlOnVU2urLxdKw1dmhonG671ckao6zMm9/Gs8xBXdNEReWGlgEiWJrKiN0tgQb3rbkKN1t7aiWLjwI+me56QjqZ/Nkd/+fvzRbW3VbMzsIANwJqhyhKOuRnujnz3zuh/d1pHqPB38N/I4f8tdMalkkfttBSbEUtFo422pwWn7h9iwBFiBGuKbpvvKF3I9xyC66ws25kVg==
  template:
    metadata:
      name: postgres-invenio-app-user
      namespace: database
