---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-invenio-app-user
  namespace: database
spec:
  encryptedData:
    password: AgC1oQ2bXinelhWLXr+NJUtS0IfcrlGxjoVQX7po3wAr6eehPeRiHwBsnH1oYTCvsqGBgwI5ZOv1UdpdxxUfNVWbUv+F76rQSoipUqWqmwjWjze2+5RM05NIWMB/X/aaTO7Q5mkRbdHFAl2/UHbAHlA10K6m1b4Hcx7QZzN5LCVGx/0b8Kc/8dDmYdvjlM5d8zqI6MiK8J99iApZZJqNJ5Q8Rl1pGHU/IRs0QNog8dgFsdfbEmMsbpkJ3f38buD2P2YnCdqkuQRBrZR8mx2Cgm0pUwVZrwMRyjhg1TkkY1tMZcs9npUUCcmWDD+9X2O+It7PM10L2h6jFCP4E0AdzRikUHGM9xchderVF53QQqrUu13pYcCsQsFKccpD8o2xBpvKpxJObSZWf/0UH5kasWz2M0vO+XzRbBLtrRcchL2Y/+LuaTW2Lyz+bzRRf528O2PO/WhAFkBadm4uGOqMkfIJLPARImpOvRo1f78XnaI6seYjU+ztbj5pD+voASnyTHaUUt1PB36ZkAzlw5KV3ZMOmL6WG/yqtevyvEs9QoI/f11azR1btqte3Nw+Ms7p0vnV0RUVgRH6CwKgG3FZpr2c/poSUitZrec0IeliYAjmGUNhF6+wIif6tTWuN8PWCc4PQ8b1TQMrlqW43OuuG85d18PoWt28Rsua0wBaPhnAjylhn8nr4vdPMZNtJ6XYiPBYPPyAB/QqO+5lUsDDV/b/q6bmUcGPt+DIuVZC+KXOng==
    username: AgB6A4JCunfcALqohqsJeAlwdzf5Y8MGo/rFAo4qMcvPecS0dT2ctXSrbRqPSk9jdzgezIEJZQc9xgFhmGhh22FMl6XUKFfDP3mHqcZZYlP5m+BTZDeg0RDbvbfU3ispJ81OABvFm6e1FNua53NCEE0QY//dNEz6bVOoXiLtUUqcbE19PG63KDrxxIZUYLbfMLI48RhsB+gQg6NlrKCUNPyAU+J86trcyBk2CVcaURrXatu8p4CC+eK3IP5vGKDze7iGiFpqdULNWXIffGa97Nm7G1uGukWfDFLhmWdEjgLfFhReP8qU4fHKrL0Wde4TyByATTTVj9G9oMaS12URndplIY+NjSROx0JAN8mYKxj8hiyq6KNuttBf3FBa/z1jIbENruGBCcrNeUgk8HOafBNE4kGFL/aso1fDN4NPkSGnEWgfXy1W/QxVp9vTHB2AZxTGEnj+mUvqrtxpECvLxZpqm82oQEOSqWvNpsGxSQJNuNfkGH1gp5pjf1/TTPpq+QLijYs32Y12tvvYrMb2meE79baPiL1vFLeubw6D5oxo38LchIdbvAND8D0Goa2qbiGT5Ybt9WpqFXJuFIfTGledH//ysNpFA91Sryf90pSqUN1CcVQncYC1kRqaX4qLQlQ8gpUCaFr8aXBOGl2g7KeQVVwmz9H7QKy3FwigRVjnhRiLMOz6kfCMVzPVpIVXPazg1tDBj0mQ
  template:
    metadata:
      name: postgres-invenio-app-user
      namespace: database
    type: Opaque
