apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: database
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    rootPassword: AgBpjOxOtwDpnirgMe+ns7GytuidMYqPHz1ToXdBHecoAD+uC871W+noJ+tRwsaz4z4zAi637959bonTqnFkgzgSKZwKMK1gumYYfSQvuD/8VQK3rwoNvHlNTYAdFSVVDLDuieFU3aQjYA4XIF7NTd/muIBSH2wNtA1LyqXHQ4pVvaKxYYNABZsDjeL/BQCoX9hQ/qQIO6xiCGtbGW6We71jO4SPILAaSUnF2NnTH3l9TSqmhGFMiyXb4NMF9eGsamhh1Adp0esCYtcCfrl+QFaCOL2SFb1AiJWjvlqk2WWu/ERrRo8rjtBrPcLOsZgtx9fXxlIIxEEEUDliwzYKO09nvL+CZ8gCLz1cl8Au7Zzlc+rkm+f8WvLnVkFuwGB/ad/lX7JbvTlPhQZBFfzDfvrHClxuJgt0lvqRNu02ZVaaB6rxVVAVqs6ECqzh5LP1mkJqZTYg+gjjfg/eQ+lk1LoyULs4eRXmZ3SPMFAXunxb/Ualrn4w+oNnScQZ+13BeUhOqxVEPKYbRJ+ewEEAiKBnq0XBL+XXHNDDxKnc+aHwCaE7/vdcCiRaOqIO5z2Osvak1OVZjqFeUrbLgT13UyoRZoiztOYJ7d094z0Men+CI6QcjSkuXWBozDKW9j/Yt6vWZZpVQEySw0awi/Oj/A+Yn4SjHwPZYVwgnetoUdzGM10QlamvHMXylpCRfAGvuPqplbzYgZkZmUTLICgOVK1G23NUpnVmYMnumFKUqhTmyDBlby+P
    rootUser: AgChcS/BZtZe3c60uonIqjmELdY0HvtkUgxW6wGZ3XTZLgmOLs/DN6e+OgSHBLL5hTO+bygiNDb7kZncmapthWDLiWPbQ3xJg5VxL6Aec6JodkQ1JWYZuc4JMRLn7eArCS70lO6pcjruiYK5dJzEvroz7vrK513MqVqEKoTHWSKekGsDTk1hJxtIEmk3ov1MFlPs81Hjr+l1it5tUhqHuibfye8wnpAyfy+Sva0zopIgKa8VZdicVrxVK3b+JIw4UtUKCs6/HDWVspXoGSDnRa6yKU2nBcAta3LAlhvtNjBr7jfhO4NjuAMHAYBtvMaEbraMEhXF1j35yOgjrhUT+xdtNQ63afxIPkhKhxZdxdWwGjmE21KmVaIXsC7oAwizGnVApTtPsLvvHQ+ITEWayOWF9S3SH4IF7r65Ysh0xJnspXBe2GVYq3tGNn5xV1mmMevt5F003Ju4oBypFkioz/m8dV+SMTXFDD5OPGuGGqV20pLxcQD1uAsmXmUEwNP5LzPazsz/osU8rAiQwkROJVE5EXiTD2C6bhynoNCficEUMMctPUQx1mSyIXa869cmHuUtKvdRlDs0nFbYqYKMR6Xqrrm3quODjhnBCKZ1uvjX62d9j6EPxIUygqKjHNPKRMlma0CdwijMX1mnqF8xfmeh2wWI5llJQTEg0wNLLlhBkb7BdMz3f5+f5IjEMAmJWxMYQTJ0nMOMlCvp7Vnx03S2g/Le
  template:
    metadata:
      name: minio-credentials
      namespace: database
    type: Opaque
