apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-metrics
  namespace: database
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgres
  namespaceSelector:
    matchNames:
      - database
  podMetricsEndpoints:
    - port: metrics
      interval: 30s
      scrapeTimeout: 10s
