apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infra
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  description: Infrastructure - ArgoCD, Sealed Secrets, Cloudflare Tunnel, Security, Monitoring
  sourceRepos:
    - 'https://github.com/vityasyyy/invenio-rdm-gitops.git'
    - 'https://raw.githubusercontent.com/argoproj/argo-cd/v2.12.0/manifests/namespace-install.yaml'
    - 'https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.27.0/controller.yaml'
    - 'https://traefik.github.io/charts'
    - 'https://charts.jetstack.io'
    - 'https://prometheus-community.github.io/helm-charts'
    - 'https://vmware-tanzu.github.io/helm-charts'
    - 'https://charts.min.io/'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: kube-system
      server: https://kubernetes.default.svc
    - namespace: traefik
      server: https://kubernetes.default.svc
    - namespace: cattle-system
      server: https://kubernetes.default.svc
    - namespace: monitoring
      server: https://kubernetes.default.svc
    - namespace: velero
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
    - namespace: invenio
      server: https://kubernetes.default.svc
    - namespace: minio
      server: https://kubernetes.default.svc
    - namespace: default
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: cert-manager.io
      kind: ClusterIssuer
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: policy
      kind: PodSecurityPolicy
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBindingList
    - group: networking.k8s.io
      kind: IngressClass
  namespaceResourceWhitelist:
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Secret
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: LimitRange
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: Namespace
    - group: ''
      kind: PersistentVolumeClaim
    - group: ''
      kind: Endpoints
    - group: ''
      kind: ServiceMonitor
    - group: ''
      kind: PodMetrics
    - group: apps
      kind: Deployment
    - group: apps
      kind: DaemonSet
    - group: apps
      kind: StatefulSet
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: networking.k8s.io
      kind: Ingress
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: bitnami.com
      kind: SealedSecret
    - group: traefik.io
      kind: IngressRoute
    - group: traefik.io
      kind: Middleware
    - group: batch
      kind: Job
    - group: batch
      kind: CronJob
    - group: policy
      kind: PodDisruptionBudget
    - group: monitoring.coreos.com
      kind: '*'
    - group: cert-manager.io
      kind: '*'
    - group: velero.io
      kind: '*'
    - group: autoscaling
      kind: HorizontalPodAutoscaler
