apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudflared
  namespace: kube-system
  labels:
    app: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: tunnel
          image: cloudflare/cloudflared:2025.2.0
          args:
            - tunnel
            - --metrics
            - 127.0.0.1:8080
            - run
            - --token
            - $(TUNNEL_TOKEN)
          env:
            - name: TUNNEL_LOG_LEVEL
              value: info
            - name: TUNNEL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: cloudflared-credentials
                  key: tunnel-token
          resources:
            requests:
              cpu: "10m"
              memory: "32Mi"
            limits:
              cpu: "100m"
              memory: "64Mi"
          livenessProbe:
            httpGet:
              path: /ready
              port: 8080
              host: 127.0.0.1
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            runAsUser: 65534
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
                      - arm
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/etcd"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "CriticalAddonsOnly"
          operator: "Exists"
