- target:
    kind: Deployment
    name: sealed-secrets-controller
  patch: |
    - op: add
      path: /spec/template/spec/securityContext
      value:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
    - op: add
      path: /spec/template/spec/containers/0/securityContext
      value:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: "25m"
          memory: "32Mi"
        limits:
          cpu: "100m"
          memory: "128Mi"
