apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: argocd-log-reader
  namespace: invenio
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: argocd-log-reader
  namespace: invenio
subjects:
  - kind: ServiceAccount
    name: argocd-server
    namespace: argocd
roleRef:
  kind: Role
  name: argocd-log-reader
  apiGroup: rbac.authorization.k8s.io
