apiVersion: v1
kind: Service
metadata:
  name: invenio-postgresql
  namespace: invenio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/component: dependency
    app.kubernetes.io/name: postgresql
spec:
  type: ExternalName
  externalName: postgres-rw.database.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: invenio-redis
  namespace: invenio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/component: dependency
    app.kubernetes.io/name: redis
spec:
  type: ExternalName
  externalName: redis-master.redis.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: invenio-search
  namespace: invenio
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/component: dependency
    app.kubernetes.io/name: search
spec:
  type: ExternalName
  externalName: opensearch-cluster-master.search.svc.cluster.local
