---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: invenio
spec:
  encryptedData:
    .dockerconfigjson: AgBhPcJkwvPQDUvxdO2qiL0ZSEJFFw1ZZ/0UzqrTyKNeR1EpqFPPJdL1d3G1FiTy720HngfjvPqk9ayz82o3ZpwCqkLEyU9vz2dHHa/SuHd+ltDQyOxrFT+aYdLbN16sz+40gV3UdUhKdRYNiahZ5gN2ZC2hOJkSRA8e1tMEKUKpUAZoifdcbLIN/I302CYI0+UcdHzDEuFiIffr4r5vBQUxoN63ODgeTpWu3BI43FpJElCFwrzeZLMosfOwrIdiPVmRAC2h8l5qGW4K/o0mcgOpnvHsZR1ad900X45B/2sIq73u4nP6lQWpHdUq+B/yKV/4i30Fa80216RQ6EQsdD6wVSKL7+qtHYOlnSOGV7L1i88CyJn9PMORuI0GJmHc2so8DeOVs4HngtA4KpjXUsGni+VIr404g3ieESaFWt52qcuU1Po9TS6FKrstX0DgVLCba2eKNTEnuXcBZTP2pUNmzGdfWlK/sS4OX3pq8d7eAard55YdCHpETHrt+u89oFYGLjlYRT2UzHk3kOo6QyfE/2UGPODOOrn1Mcmm7ZhHV2Zk/6Gb19acRIFSJy7tql73zPoTfVlfMrvkwiTfImT0ms4JX8aj8ktr810apVwK/ijGv7PaqVpTGImTwJ7Hk4I57C1ebwEHh4p5COkleeq0Ve2EvvyrHdo5/hOkgw2YYAIg+uRdUalvd+HpeZCCuO83TX9ACGmm5ra6441H8kynaBnISSLry9aqdIpzDazvZd34f/v5FVCN801xcybdfRarRp/291cNbHnJUrz+EERp/YArTIKZwP2xH30QktILPUZY89dfIsL0w3C9Qfu6/FDfICEqbKkot3I=
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: invenio
    type: kubernetes.io/dockerconfigjson
