---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: invenio
spec:
  encryptedData:
    .dockerconfigjson: AgAOq2TyzaX1T4vmmNZeAFdCStbNBSTlu+Hn1YwLwkKNb2bBbrq6qqx3vujKpd8e/NMVVA1lbze/OxoUOQ4hp1FCMF2hlLaSiPFI2HGzOg7S68b8/7TmPy3SKQsr92f0vuRc2dZcklxChp7hInguljz7nJAdrWqRyYDGMDa4OYWRPEnVrMNaRgK771p0nfnAAg8T+n8mXMwkrORkG0+55D3CARLdXqujIi5SNpJz5zZMeg6hT8xZF+I870bTmV8XOJJUwUMPESrrf5U3hey2y4WZWs96dnI3r9Uz8IIq9CbMOXPsvSV81ldmUuwpZqzo5DVOCii8i94pdurrjXi94fkpoA3b/DYMUGHS9cRAVhdKtqQrCzPB0pu3ri1HD8IECaIp1I5Hhw0S1Jk+7dB0BhR4Ieiut6vcMO9S1kYP/9ltOF/kppNfuaal8m7fzN1gDkbOoeSXRsvWK28k06kGa2f15Ihy0+fCnyvtlBrbN5GBlefyfNcbxluEgjZxNyY5R538KQuOY5EbK8WsrsIPlVKtT+ylJs4H0B9zSqdkasRFU6uMhnlGvwglmIj+0BaHqawgOa0816/vnA0nhA98oXI7YG6/O0uvAcLt/teB9ZL6/dYQkDKffg0QDa1gcy24+IU9EF9YXCMCwsd3imyylxSgD/ZJ7cFJxh/AQAYp+2u1hbMevKc+bVA6fIjU+ZdStHCr5mwwmrSNl0JA1HgkhJ4clMlLlfv+Sgm4G2dl4TkfurQMXR84t6IuM9pma/Ujaornu8nSFpuBNSOyG+VgfFUKsZ2NozWhEiAulsR8X+fjfBtWfZycHMqxiujElweSgw7PeyridN56Kr1GJdS/fXEZf7mZpZDrx9HjV+4J1P79X6ruQDhFn1Okt4i0PD0qQa2p/U7vGLqbfsuGJ3QcYfBLn4q6o0UlJY8TFYbxhFz0hFbs9ftuD1FAwea9Co5ym9nMglVFepESR2Jh0J6SFuQm
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: invenio
    type: kubernetes.io/dockerconfigjson
