apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: invenio-headers
  namespace: invenio
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  headers:
    frameDeny: true
    browserXssFilter: true
    contentTypeNosniff: true
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    forceSTSHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: invenio-ui
  namespace: invenio
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`invenio.vityasy.me`)
      kind: Rule
      middlewares:
        - name: invenio-headers
      services:
        - name: invenio-web
          port: 8000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: invenio-api
  namespace: invenio
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.invenio.vityasy.me`)
      kind: Rule
      middlewares:
        - name: invenio-headers
      services:
        - name: invenio-web
          port: 8000
