apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-config.yaml
  - namespace-governance.yaml
  - dependencies-external-services.yaml
  - app-sealed-secret.yaml
  - ghcr-pull-secret.yaml
  - serviceaccount.yaml
  - invenio-deployment.yaml
  - invenio-worker-deployment.yaml
  - invenio-setup-job.yaml
  - invenio-ingressroute.yaml
  - invenio-hpa.yaml
  - invenio-pdb.yaml

# Image Updater will overwrite this block with a pinned digest
# after detecting a new image on GHCR.
images:
  - name: ghcr.io/vityasyyy/invenio-rdm-custom
    newTag: latest
