apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app-config.yaml
  - namespace-governance.yaml
  - dependencies-external-services.yaml
  - app-sealed-secret.yaml
  - invenio-deployment.yaml
  - invenio-ingressroute.yaml
