apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - minio-credentials-secret.yaml
  - create-bucket-job.yaml
  - invenio-buckets-job.yaml
  - minio-console-ingressroute.yaml
