---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
  labels:
    app.kubernetes.io/instance: minio-extras
spec:
  encryptedData:
    rootPassword: AgCCqUMIsrbjmnZF1/6eRlUO7qFgcG+MnuGEuTRqxc+nHukPVRX3a3sUmrMy/JK/uO86oTHETuQz8Sw8DYkEqPiGSEzzF4FT4NRNJR6XqXiFZoWqGZFbDOpaFOuNFb7V01JhpDwK/Wi7G0K2ayIWq3lgFYvtppDXLDVnMNVmfIjPQj9/OTU7l1ayjSaC76oo2qq/7VeOjucSxumn0xF+y5uZbC9YLP6hWl0ySdG94s1lokMn+1SFzL/p/fpLZUVJnEsS57CMT5eJaZ1etKblf6gNyUkeMrN9ubJeeNzXCRXgZ24WIftvg7qt00X0ok1XUiJueDNOc1RXK53OIzcxWHyMG0zkmAQJnfDhJ7GvN13Ft07nZZr54dzYMdDPtdELSuolUbG3kpkQGQ+DfjGJjKKTsdPD5K+LYR/TelWWcTozOyFYEYjW7Wnaa9H7AONNyGYuSI0P/wIOPb9Sql2qH7J5VgvbzQ/Plyuj5ge47d8mPb9xYi1hYdmc+C2cef+kgJYbiIpVhkL4KlU/spB3tvbgKd2JG2HuO+QthhP794TCqyhIkU9zqTjmrX9bScSR6S03rI3VwFrtEsf2EL3NuR23YYFOJfzSKrWsxLV/eZO98Mj9M+4IFMbvW3sJBUokwMZ0jP5WV6LLc/ZyPStrR2Kd6BBFXi2kPHnzEnEKJBqOW7CSAPTDVfKpOce4Y8AIoYNC4BQEwGgET48b2P0wR2pfQKOQnCumbG3QrDF3RskQRwOW0D/V
    rootUser: AgCI6Sh4pQYQhyT5LqvQJ9kDFFYLD95I8bWypBJpRkat+NUSOOR7OmxgwHsDbmVpef6Q2qfofM/xgEtWlkIq+gMjp6J2SdWPVFiBarTUlZdXCoI4mTRH8XzXSrlnpUW3Wqw3eb1rEfm8lh+VA9lDaiEcQBRzYZICMiF26PNSKH/vVTecGwLprO8JA/xzkvdxvrtlpeVJ86GOq0ZKLOaqpH++f2s5IFFeKM1iIJDcktFFv0Wr1olfSozDeS4GDLP2z9Sq7sM0qrLhMvCpdQDj935CGnYusjUoct1aG1d4Jejyw0y6Ui8HTTHygdSpye+2LJTf3ysqwuxnFtiOY4ksWT1/qcnl0YCEf3ElvOHjuYKf6jBfTQmHwh/QB6Q+q8hBa6hRjppRnqQ0EGtxOq8adFEYMTs69gcwA+2HH2HKSgJfEgZFz2jPxKT3b8k23cBNGoAUqxcZLMl8vW84/qMk+yGHlrZfiBO6wMFdN9u8gDRGYN8pr3NFTqD28Zo67LWdMVyHIY1wwat40IrrvWAl3+r9myco/+18mw71gBeg4jP24y3AUtM0UAGwb+jBt7ExoL00OmGYLmEK2UrASv0WI3N37CxMCpRr5MKiUxdPAmUZx7dIaSOiSUkQs3OlnzFIWLfr9J44PNp2CbMOCJD0rxKGS18IYJtMsG98rvBx/VukHRb35Lhv3OIsYTxxmp3PQgGoxbXIr8q0Cb2P6WVFjh/tSB1c
  template:
    metadata:
      name: minio-credentials
      namespace: minio