---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgDI1H4RtKLTQX6wPdkhk5svVZ/mq/wKQzlgjqyqMA4/n4AEC5p8FmbmlW1NP4feF1hhNQX3UBu/MHbqT1n6XdBS6fyaoM00pz6/PwmEh1n4IlLbiO7e7vf/4LGGFi+1Fh1ZsDTun5k/Iv5LfY0YuG/um97gGimopmWt8EQZ3id3eG+TQQ8mwopLKTu7pw2JJTHauoB/81oM64aiIoMRo7y9Djf7XgiZrn3q539Qmgp+/cVjm3rPsj8MTnQg9h9DyhZo/bci/aaLG8kbm4D0GcshsCR0UhOhoUeSiDhIMBn9juTDo4Bx032oc9TwUlmQIQWiosB0gU5R2XxC6LUfQJ0mHD49rum1uBYF7cm1UdnSM294ffhryAW/DpmAemjiynbeyloTJlFscHWuCmtBBbRKlcJiBvZKLarlDcbkn+rOW37mM2LkPKXqlOpAdSPIznrZ3+W0tA9d6/+y2vWSSG4Rn0UjTwMyOVcsQBU1vqrlTl+9wmWM2gV39uiLoj27aJP/cPDnIDnWNFFINsDRLEsW622pp2oJz3UOchp/Lxei6OXJ77Mefqr3UdOCKod9u8b1rg29IDShBffFoqkMQJnvMD2dWgCKEeT7Lf1dfVGMpqXjl9sPaXhEIFbY4ZTkrqwezG/7Ih/SfvLywNqAqWGJ0wBYbTuSUb/Cm1CR7TX2MHKPol3MYmwlsLqKz8SXlkscQ/u4UmnZTngcQAijh58tTovFwuYEAXZondy3Xl5ma/kdzqOITw==
    rootUser: AgB37kisMgYSlVtSRqKBbbumxMOqdVFV5iUMB5Qs8DBXhpmy+8HmaAQciAB2m0yYNdwur/eLh6h5auPFANRV8qSc4IhGlAK0pvextmCCg0rwHNFzm/BO8ZOJ0EID08bES3OgxbDhlI5vTcCSqvHJ0HssAQ+SLJkZC2Qm9aRYXuyeCv1nA+pZBx1cnjcQwVx4AIzd9M+vzDLYE6NOYtQb5pCzjbt1n/KJBns7O60Gptw7JEyjmFKbPZilIwzNIpa/AjvHlyTWks8Mgm2GeQTqrsPiMBY9tIHKGSI/5QqYGGUi8QGfK1/kcDj5iS7Vndt5+gk5NiEw072WAlefcOldeTkXyARnzEezg3ugVDa5DRVjhQKroIKgOmxzKmsRDNjMI0sj8zi3z/J1htQnIizq2UGV8B1EMfGVRIMCf9QTCak73vutC16Y/7aK5N99g/BLwB+pCRmyI2kJTEi98Y7LJcHZD4a2UUb4ZmgnQbICoW1Yt92OP/j5u86UbbSnpO8CJStL2uaeQD4XZXXp1MMGXzZJ8jpp8K90+P3TMxFIzYR9hQaEDgaWsuFFcDLn37St+I7zzttwkU5Iae6Pv2K3vjJ5QCmRotFD3RP0af84WFHIpbHOIY0xRbqhNgb11I1/US2u9kIPH773rK7kTUeFeR6jDnvO337oW8nAVEJs1Wyqpe6MqBm8Ho1etl2gLTaGJ6KfLQw5Pd3R3ansFkKFRS1WZQpt
  template:
    metadata:
      name: minio-credentials
      namespace: minio
