---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    rootPassword: AgDXZTYGF+YgwYbC2Cz3UX9RTIoe92iMBe4fc2kyrIhHrnqpwTMfbyl+k4UKzHlTDvBxgKaesKFaSayZ8FOIsDqrLWUk/2FgNkJmf4QsvIKt+IMs1OdESHnA23GGSh2V0j0FyrHXcHF8flXf1UlCZ1y+kC5u3VDrgY8mrXFtuJmtQcNb3vkxA4A+3wJpnh+XwVNtCspj5EvrodowpFjJ4KDIvuqy0tzyVbSKtnTcJABvBu+jRRbZI2uhS88eQVk3MATs2IAB/yssKg8hYPGJqf22c2yfvlfgj2tMkF94MIU61mEyZzFl+q0hTD/6KXY8lnmjA4CxyKv6usRJF0GeY5x9t61XCEc06nXOkaRZwVhK2G4/9gtKnzsiPvDfsjXxJXsHeAgvxWsR+lIfmQ+3hHTMytl8O18jMWLnd64Vp8Vvosuxl96l5HHoAeQ5MAS9rZmP5Ezc7ZAUKURsNd391bHZS1FnCZ4/fp0AA/+cTu8HnWny6HtD5pf+46ZXdphPboodOHEBhR58elwt9yLdswoS8/KUvbMqXug4jbeLXxztfakW0JSlO5VIv3Xf5OA0GTx93d5HB7fCxIIyXyyklFhm37raYxP88v9PIUV59ZazpmV9KaC87dDXW3ifKMa7q/9r1oslxm+s3ep4BXINFoBcIFdcTGEoh4rOiiylU19Gg2AQObLNiIgEJq8lXMief3iyDrWRjjW4sgvQNC8iGKoYRdYr4U1J9/N37zwMKjQHkzxSvmJL
    rootUser: AgB6CrHoLxfZKuQRckOKHE1mnY2hobCYxg+p7N3aQVgUCDLwDmz/VK2SxJLVtk1+5s8fXN8EIuTQG70meQ1+RhwWYub0mCbnWX9R66mWGRMII/MYoVVfOhZnse5YO4qodrEbdsVbfK88LcKaBo0sDP671yweBeng8kXs92yp/4oWp0mkVcf/MJ4CKTYSo2fYL74RMUyHKZFH+XgnIfjwhcTACchS2XA4Ue3DzEJjd5nuozYiEVbroGAlbqI1CtqDIsgZTnqQWstkb/kFgi78NsqIxoxObAmVPgFbIhb7kJWM78cpeF27e8ruBszxcf3qBK5DnbnGFgrjEAK6agwTMHpZr4IN3BZ8hLR5IcdwXiw7s+f0PklwvYSB+PQBmXyOp1CRavDKRjhKTXsNe1JbViHWc8+n7NMJ/jLNS3vcsSUfGUI93ERXfkO0i3/e5Hf8+a4COIpYl4BqHCJ7QAP017t4NBgIBWqeVff2h/OFda/fs2MxyWp52srg6eSOVdCQrKtATIP7IeMP9VwRD6Iqr+mG2c3RMIDv83kZQbb3b1ZxTZYl1/xWtgs2uluMGJVjO2uPXPhc7hlTY0BijJGWDzRckFAdzmbC1DC6lmbJ897CUkveIdYFL8bR6K0bgMTXu47Vg3UNJMC6FWmxNsRnIA9LvuAWtoud1QXRr3HxJwejdJQViG9Xm37Jmf9xpdJZESCxjbtbFax0og2RQj8YuTqG+uFi
  template:
    metadata:
      name: minio-credentials
      namespace: minio
