apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  "server.disable.auth": "false"
  "users.anonymous.enabled": "false"
  "statusbadge.enabled": "true"
  "account.anonymous.enabled": "false"
  "accounts.github-actions": "apiKey"
