---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgAwOPSjfnIJKO5B2ICaTMFSe4pxPz1McXgb5xebisibA9B0QnpmJqmlQ8+X/eoIP1b9+0XeGztMyLhb/wtXZnzkHY2ifk1czLQHFvL4t60VFdCBa4tRhfHsqHCSH8JEj2krRVbgPhUP/TG6IKDWcnEuJLDoPnqOdWY7U3718A4Hk/tbt0Lo671YWFATJ7HBnw3ZUPiETSjM0MhjszMuBmMOdHta3P36c0+RewgXxeUFpLLl7V+6+pzI4lkTMrMBfy10GgnxjLHJ/kfKneMZ3Zkw886OEoxQZ7mt/y4Sb8uima/Ej6dEZWWL9OjXoJIvUYzxfctNYaiArNcyLWE4g5uUQOJhOaCvbIJBZg13cOUYeUEyszkNWbM+aqA/MfnUg47bosb0VITQ3MDIbnj/L18W7TUEEeb5HKoWqOk3TluP9J4Ecmv32aqe+wHA3j4nVwGP0WMkm07GmGENGmJ9xlOTCEoZQBUbG3VWBkFmFm1tvhvarMM8GnS8FNUBexQe56QMdgDB9IVkzL5dHVEP3GqZJo/n4oz8w4FWG3aKKfCmYlaa3axv+GpbRowrs7lE1w59SjwwLpBeZW+4rJg8hs0rF5v9EthZRL7jf6gCyyzoTTl05TOrWK6+Zi3xrsSosxX/8iE1FXUETrJ1LUg2ReioE6JuPjAK8y80w0eBAF1sY1IAa41QRJD0v5eh5GYDd2Bl/bnJuNF5kMAOMjIckyiwYZtEfB1dU1nPub0vR0ELMSNACjfF1kR3RJEJc1qDl+XXHtbVuevEr0opGg0h03zi4w7ag2QMoIHCFqsgRL4aKR5ZZLZIf70Ablxb6y15wNBr6avBYQPiY9rE66A=
  template:
    metadata:
      name: velero-credentials
      namespace: velero
