---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgDW50FiLMhKUoaVpAlJqV0x8B0jqiuKPTioRd+0B4jGSm3WC6xUxhUaqRXfuEWdvsymndUgK6wzJSdu16BqLs9Cx+Cwg5ivrFJLwFead0b1IFjosQosWsGnGpvot3usdxMB9mOzzbOUpoo6s8502aTl6xc4KBJWKGmcno0zRtHp/wzDiPwLnP6TJbr1xUVeFji2hkUgXpu8TuwypF6Z8QfFKtfYoOU58CaKk/hzrkIx2H0QjAunU4lZcrwDqbKDtsB6ULq972NpiOivlwmjkfNZ859QMMHDQY88phWhPTOH/MnGSpuTqNeIisRnR+Xdq26fTLZAC6RDc897mAUrySyzjB+cvDk8ihMkLSrq8y0GLkKecwF4hh+Ck/CWMaoMS5gjNDlUSVExV3P4eBKH6WaX4KAj8V5Rhi5v7DZMEGbfoZSsBqZQ2Z8b1dBDFC1Rjq46uuepH7OpE2RSW68JK6X74PUjYAzZR36TyGCq7AzVoLrY05JvmG9+BJwFjiouhgdh9GIAFACWlNOU7iwWF4C1BuN173sSKeCaIbixmK5PXELW3Lxf5XldR4IeixypnzIJMb6NU/5M06WbSMYl5Ah3o8U/22HPleqBh9341k6FqmRuKK3MLBlw2bL97rv/ibOYNibYEycs8QFX84RiE6rW7ExKOMEaF9AZMpUh14lufC136Xj4yxbe53jT0Jvf4AHSQ9+yADBiILqPGLoTw9DvbvGAoDt1R8wbgnoEGqYX86akqbAfTQii9lsbXdwqVHr9piGLrYyLytH0QQehSy1Z/AEfLLANJ8I064lahbQaiVw0yiNURL5Om0KdnvouIX9j9VY6flbIpYmUNg==
  template:
    metadata:
      name: velero-credentials
      namespace: velero
