---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: velero-credentials
  namespace: velero
spec:
  encryptedData:
    aws_access_key_id: AgCbxP60xBvGQ1veXMn9VjgJYOEsKmBj2qCO9U2a5eu7Hjl7g3mvbr1etZZBEx5+19RlTryXAWjd5TvdH/Spa9fcj+d+uifG9ngddqnc06sqobtOzyKoSsadw8ScmuABkHTR+t2uR2ChlaLsai3bKAfrN2VrOV6+Q9n2ko6LoSHZtjg1noy6e8Xpvx2pjUk0W+NDhy313/gUqg9f7Z8rKVlttCwKfBHW6bDg9EhU4Z7JMy/+FSMOACmsPvAMDB5jMvX8w8HyAlg7eF48PWD/4LVxgT3SsBNJXH6UNBl/YIzT8kjhdyevtTLQb7hGHsHP9CgFAdOKG7V6fcSlnUnY3f2S0IdzbGTAH/ZhQ87zGA9/yy8HubQGkQiQDco8Dv+sclK9/+LbCGjsvfpGFg08CXHywDahvrOVdVx0vF7/aSaHj40p6jkbCziEB+JSg6wUOUVowqEu2/aY1JkJQVhVSEpte8Wd1BZKgfoKwuq5D816tfC8RqPqOCaaDybYnsJjua1GLnoPWPxcINWkf1rGG6ivuR2L6H7KABInc+RtHbEH57bRXDcrzw7iGsC1B52UQ71tpcFOFwZJy1SKfWd8Pbxve10YBkUBMqpGaURp5qhqWfTyIwtwrslPAYR/U8pG6pTYqYG/QGDzpji57hkxsi+OY44vRf3+wioKboe3La7bR7WclcCuPFrMLs0HK/TGFWUk/spuuS9qDSLY
    aws_secret_access_key: AgAjt7e/gqF34t+KSm7BGMeakhmohvY8hm7X6QcFW36vNtQ4nvh4cZqQw8+kQ3c2r+hrOInfS3Zx0/PRUHzxfAsTSwRSCH7caPCpJlf7B1aDpnBiC1Yxu/mQRSpkpLCDpr61RcmlSQ1XIkBjVO3mrP6IpedhCzGwAy6EWgnq5XpZbKzDPpd+YlWB2cdLNP90pBeW+Xp8JmgJNeszyTbb9m6rHtv3z9ZUXC8u0Oc4EI9pk0sQsmtUIPxuzZl0BerF0uJ+GtsHVnCtW54rUAefHG00mVqhbCWUkXv8lkNpk7AOw1cXlg25JA9zpPH0sTg6Apm1CvMTqyPFfzxx7P87eOCi5oZl2plTcHTzpLbKdfSj7t/LCg4atkneAvd/NuPRHFeiQtPyFRDDNjW8Dy+4yazpF46cZYhrN7QHGUxqQt6+KPsZWVT6qWTTIvMuBCVZ/BnvRFEeuYgUFIK1Dueh6R13YMy7AP/lDK89iTifdKluj9aScRtkkENRMFSWIW8OkFCUydAQYnmwPXiAFTNiqzyzhbCIPp+hFuTSc/Dd5X/Arkx12pcAFkOOTN9afIJQjF9w7CstmxdjshbPAaMuyWXEH60RqiMmSXPSkW57fbLACQePWxhpXfJxZ+P9BmJf506bJNF4gEmWgEddhWnRrEO1sko9Ak0RplRCvwzUBPcaqC9sAZIJYznxUzBUFtuq/M+BDWDa8q/tw9iFE0ml
  template:
    metadata:
      name: velero-credentials
      namespace: velero
    type: Opaque
