---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: argocd
spec:
  encryptedData:
    password: AgCzRbgFhHp8y818Vbgy7Wp7xTQwySjUy2PFr32Dlv62E0DTDkyziJrZ7lqYQmekl8NBLD7PXlPi/Oqj+HJlDMzhe18bbCt+Cn+u24Gi7kf7+4uSLL7j4HhN/eowlZN91Jc6cRXVduSzZtGeNq+0T6f2oD2VFn3ySxW6FiV0Va0zOiP3HbBXCWP2Nai9qGZnLIfOSPzv5owyJfaEKMiFn6JEyw5TpGol8eicZ44ulmpmgB2Tfk/090s+PmdX1oPgCq/Hgc9dT8kVt42s6yUlQjcvC2lwMWEvvo0FfAVRx0ApoqSAdODWuuy8CyXjDekXYoPNx5Gcqo2eTReGLbUjGxnVtzaBok6nRpewv6jhaxryFmrsSPov2/hOxHG90INzF2dYhZF6p+c7aADcxfAlVDrN0w9ZM8+fdV7/LGVuSwLQb7mSi9hkLXYrKmSQnVvV5meznf697oNPtm5w8dGKnjLs+xjQZ0vuZJql5U7513aeZFOyup3YCD0Rh0+oDzKjka9zNqHggasu1yNEW4s96vYdEUqt4Gp2P6OQ5rTlKe477w+f3K1VjfZb91F0ZAT1sZyxrz5zXVYNzaqlxgTjffOdGZEa8FefKOV8b2DvPgonUys76+e6DC9of6r5l8f1avQdbz6F9ObikKtmf04rvKmzsVQMm+CpBDWEJxwDAoxO/6DEIN+iNRJydRh9rZ+KrfEzwrp4Cs/XSIU7E3fnX1U2gMdci4ny14GsW/ccjpvBrcovAlxM4ZeO
    username: AgBx8s/D5KL+HaVtzqMifNPwl3O+gdz5T57eEGkoz+BFu4i0vwlALp6cAFtmbjIO8dqz9N+CXGG203ux3Wm6e0lTMMTKpJnbNVgd7ktFAwnO/e2hUXf85Sj7bkz5vZ3ThfVrMawVvb1XoBzoIo/sNq7EtXMiogKvXGkQQamkN7oljVLL6D2y5YkYRQ91aFk7hMlGHAwC7NrdxqqNU3p8END/Xi/BUU46WCWFZoFrKcG19tEM0pqUSgyniFK+SvttFLu1HV566Q2nc1iLuknbyQmuKh0w/+1rbfkxkLEUCPLSJ2gOo1jlQK/zvRhGSK6EeIPcqyl7U5Cf2s0c1yiqjOaPLMIyLnueL7AndTm+m7qf1+r5my3BGcF/zQmIhpKRLD+BT+C5mUdLD+gqhmcvTutEb6O1UKCUw/HGRp5frH5A87jIYMYGUWjbJtVt+9O19CHksTx8OM5fX4ANv4jvJkVfUa6OpmNGiIJlEfkKx/e5SpUsvNKXhKrGq1GJzCeTq8EFbBqHQDqdofsyF2Y4XH8ZH3dVRsCwVNAPxJI66Que0wh7nyRsvEAVEugnTVFbwGRjT+vDNqaWH2lMGkuVR8Jr3m4WsdwuMpcwOaRUkGYg+56DzOoq4dcTydHC3CM7Q17xkPiRvuV2RG5wI98PZvYnhtbZLukjnhF7eh/nu/MRZ4R2GO32nt7JvYrO11I/uanbx/xOGVJ450w=
  template:
    metadata:
      name: ghcr-credentials
      namespace: argocd
