---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-credentials
  namespace: argocd
spec:
  encryptedData:
    password: AgB26TxIB0fuM+u5sIZej9V3OiKGDJKGdfnGScETd+UGwdjzdS3C/gO9XmtY2qILadChbmAaUgJ51UC7gaflJ+Q8k4By9V6XaFo2/HqGhTVKG3tQSsyfK1KmrZpU9g9zAayduhi4d28CS9xV9zTZCzi2UPriJBkvPUdect78Y9FS426WxTamNpAaYz9LUo/epgrrLBeQHZmaNasOlMnw9vpkEaRWvGSuR80h9d88p5bnlKG72su6zyzvSW2sEUwTo/9UWAXVHM5y5NIVl23WVEZfaLFm3ELe6/Hes37xQ3Hzm2SaP8Hlsv85fm6yCU/hJjqaw0v9yEmwuR4Mext2MEbLijw0idvwKWy5NZyo7J3RuIrZYLtr99Fx7AXvzjZEBtxmAXeAEYRnXWfgNcQFlWD9YWEK6yh3U//fb6SGh4lllYHetB5o+gIsiNac9B1cjHjwersnFwIctQ3Zy4QDYU3qsOMa3l4kqJEiAOEwOzoDjyBmh2PrDlKZlJw7PKhhlmE5Fa9+nHF35/nvHA2/b7dh22yIUQvWOxVYGuvQgMPHk7sh63EXNLAp1RqtbgHuPOlRdbit8xC0SjpDMms1+isa7JkalFW5XdsGzuWdaZPT99ktBVEOXRHlAve52ougBfePCw0fM4X5YHynstJWHTJ8mr7mY9PBcwYRLC8EkffPsOCBe2hWUA04OCauS9SA69I3jzovhucq0w+Hwl+gwbbZRLfkWDrvIq2j0jc0j857zq4Qx9WuMfYB
    username: AgDIIg7AtXlN8heB5rgXsAKEl6/ev/7AnH8CbCkPrbwmGddE9NodhyVN4CovN/glfwgwrx/dbwuZqgHCMeMg8JKlY2xdyp9iyg0aM8t3PodV3ESvmEWXcPDwF6kSEg56L5wMETCiR7cyrNrXd+aFuurSRKKCPwCwmf53UxD84atbdYm8RJG1Ij2wlOpJchPKf5ycOY9MHyJ5AZ3af/CIHg+MyR1QsMoJVs6wvzFrr3LlvAaOphfRCGSF9RxDw3modNJbMgPOoXTjfqCEgIko1cdRFXsvWfLMBaeFwaxdy7Hf5wJOcEDhO9mWMikESQQpLaLYcR2UeCM1XLi52BwLAUkfYH7DwA6j+LAewG8Ugwn/HTEx1QmgjXWtp6hEKZRD5KGNyRd0NcpvtnsKZWjmkIyXFId6PZAniF9O7bST08gmJOp0+ZUhZT+JIMl5dK4bRP9xAN1LtZYNcJRnSQ8g9lLoHwf8w/IVCVn21bUMTQ+sE57MpJt3ldRVUIwftoeGMf7zD/aOSW9zjDMoQky32/SlhW1vvNKB7W64Kn3LB7PNJ8lG5sqsJFk8M4VMcKdxzjvBLZj5ns/SSKXpiDBvtSOoT5pTmeJMHRdFcc2UwxCxPNGXhfgQBZ+7xNBY/iSAOlS28QEVrrElWSHwHqfD/YyY8kFrLicVni4hz4yA6TShBjYnSYMJl3HYY0Lv+c2jbAn1SfXpSrtycl0=
  template:
    metadata:
      name: ghcr-credentials
      namespace: argocd
