- target:
    kind: Deployment
    name: argocd-repo-server
  patch: |
    - op: add
      path: /spec/template/spec/securityContext
      value:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
    - op: add
      path: /spec/template/spec/automountServiceAccountToken
      value: false
    - op: add
      path: /spec/template/spec/containers/0/securityContext
      value:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
    - op: add
      path: /spec/template/spec/containers/0/resources
      value:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "512Mi"
