apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invenio-opensearch
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: infra
  sources:
    # Helm chart: OpenSearch (values inlined to avoid extra Git fetch)
    - chart: opensearch
      repoURL: https://opensearch-project.github.io/helm-charts/
      targetRevision: "2.32.0"
      helm:
        valuesObject:
          clusterName: opensearch-cluster
          nodeGroup: master
          replicas: 1
          singleNode: true
          config:
            opensearch.yml: |
              cluster.name: opensearch-cluster
              network.host: 0.0.0.0
              plugins.security.disabled: true
          resources:
            limits:
              cpu: 1000m
              memory: 2Gi
            requests:
              cpu: 250m
              memory: 512Mi
          persistence:
            enabled: true
            storageClass: btd-nfs
            size: 10Gi
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          roles:
            - master
            - ingest
            - data
          metricsExporter:
            enabled: true
            serviceMonitor:
              enabled: true
              namespace: monitoring
              labels:
                release: monitoring
    # Raw manifests: namespace, netpols
    - repoURL: https://github.com/vityasyyy/invenio-rdm-gitops.git
      targetRevision: main
      path: k8s/apps/invenio-deps/opensearch/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: search
  ignoreDifferences:
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - .spec.volumeClaimTemplates[]?.metadata.labels
        - .spec.volumeClaimTemplates[]?.metadata.annotations
        - .spec.template.metadata.annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
