apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: invenio-redis
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: infra
  source:
    repoURL: https://github.com/vityasyyy/invenio-rdm-gitops.git
    targetRevision: main
    path: k8s/apps/invenio-deps/redis/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - PrunePropagationPolicy=foreground
