apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-extras
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: infra
  source:
    repoURL: https://github.com/vityasyyy/invenio-rdm-gitops.git
    targetRevision: main
    path: k8s/infra/minio
  destination:
    server: https://kubernetes.default.svc
    namespace: minio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
