---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-discord-webhook
  namespace: monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    DISCORD_WEBHOOK_URL: AgAE/cFeJUe6ms7T1vUgQW2aCHxX7ImZizD+iey5M9rySmO1AJNtEjYcnq75pjj6N5qjGqFbX6fz81g6znyH0PJa016dphlnku5GtWKq2YazuXUgJVlPy7ola5254bec6vEUf0dwDCR5c4AL5BoUiRnKNmGEDOidT2W1RufH+pgsd8QyVXh7vIGkEbzdxC43IposdIW5Sn0K6/YrUpqO1QySr8Sck00GF+VVb+tKVhg5RErqLNndLXWtWrs40Xy9XGw64x86ci07PrlHx2dm6XhBOe2HRbFNAhWP60cjTbr6nXhmM8iNJbGwxdp0cnwRiY0gV8DOsT0pbzRpDKPfcrziL1LMf+ohJsuNLTGausePY0KrndAKywMqMk4HhY/VLio9kdrHgxxrKLoYFzuWyPnSnopqIF+0Bs7MzlGpUnI4A83KW9Mniaa0i3hJ1tqwhAkjaM9GTzodaZM6PqGWpqDiUFDVoAKA5/nPjkKjXNf+7Ae4IhTY1rWUstAICuy5qI3WiyG8qflsTfSfApt+Sk2TNWBcn4tEI0d3A3y00ATHdpgo20LNW5bcMTVgp89DoI8sBpopj3a8EyWGsoUYCs7zxKcIxpy8kOf2I8z1Eg0p6WRozV9rn0vFKH1SuNK1TS/6j0o+g2rVEoYwbeDuWXGbc0hVSHVJGwQ8NLAhE6eZqIQpw7Dy/l/X2l71slN4CVePFnL3YS+5DSn91WAhABXxWd/vh5bE5YcB458WjSnFa+GMi2MWjZTxIpUlXISlQKVLA/ryuTCmrm6cBknUG6xRYIY1Z9YOvUVv0JsiUEYCmVeW6HaS0612WSBXN+fCRr/wVClCx+OJcQ049an4lzYPBdFggwoV+Tmz
  template:
    metadata:
      name: alertmanager-discord-webhook
      namespace: monitoring
