---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgCb7i5m4oVhjn3CjfCCqYyyTxEAokqOmebLREPi5S+9Ql4qAdXXXY7UZPMh6xQp6v0CwhTGovgCtmW4zy4Ms0VAkwhcrpfa2yNmbvH8xzeTp2bXBTKofamSAGjT7etlxNViIwEAY9ccnbUQpLfyPdoYhwyXyYKoAlhI18XU6vPmwjCBs5Ag2fr2VijSDDx3UCgdlVrNlg2Ehd9UY4JKPoFm/DzkISw6OAEtTp2soc2uOMT2aKx7/7xkXyMvVg5UuCoN4OBM9+mHAWt6ISMLPFySEPyI5F7rWKCdK2k+QCBNxXVzy6h6Kn8LDERuTvRrM5F2+hEPyARWiqxwTFf8c/wmUbIDOHotp6W78yLwTR06WjE39Wf9hkUlGla+XGgD8SbFMJ03PjIJ0Aeu++L339glG9gK5OHjZ7/Ja0dqZYbgRQVtyhTe2InDC/kVA2Y7wL+w428wBX1u8k/uDsgFEgSpXbBcKiJjmDEm9BGOIVvIPN8bJrYu3SXdOb/FtRR+L9khqQBNDQJtUHan+SsZcPwxk8+ejzpCZycyOcFGfdX5Pj6f3RfSLx2TNty76wzhLcxkno+MxrC7DwGQcZG2i6gh4bWSduzYiVor2PNakftgk/fHj16kUqvWJDVwLVZMpKn6DlKfTQzxNLryZNe3p74U3bEGWR5cLWmaZWmorBAioSf2b1G1/yATBwlF9b8bp0DXpyfdt2zyqcprFfrJIqpHV8PbJyGxZu3jUO+K3/Uf3cgwzEEV5w==
    user: AgCJnD+IpBJueUlJFRR7+HOElli70GPMTrTsDYHxWiHT6mzMlGdYYpmLhWvgbGdShrkgugXnki9vRUJqJevC3M8sou4je8aKCqPOYblt9iap3Ml3LCwJN9EGHlJAqkmyQaFkpMqudWT/fNGnZTOtZqY/gC/vqPRqab9xH0Ih6h2wu2Ytr6wGDRo9+sxRQn6YCb12aQ8RAlv4/pKqSbRAjG6c2F76UUQ9J2nB4kQME1cqjp5rQ3ZI8YLTuvYlFvXblnIzMe4KBbxs1g4fmb5/T80pNtBRJE3d6WWfiNzI483ogzprQZnHV5afJVl9GT49jXp3DyEL0LtQlU5taQTakiAcoMDE+Y2IpSAso7vaZxEletsnmK/Eyd7Wo1xYKVJJ1jRO4/lr2ScYq8FeQi0MW1qAsWY92cIbqXEtFYs0+bB0Ve3Sp9klFA+AnrDjpKpIuQeFjKCZXxzlJH2y7LQQzhP1BqXS9p2mIVU8Ht1SqEiQ0sEaXFUwjTTsWzIESFmrBHmVi8zIHhSAoBjiOBn4yLAJOhU/XyQ01U5DqEYHsKbsK0WywjT52YYkfT/pUdo+7b33yYqHFK/p2HwChRxsh/PIr4UKuarwTYinTN7I2rzsY5K2L2CYRpmruJ1KT/DChaKopOLZKPfthuxJfRNw3flZilASBAeieMyu2paihnZrXtolJOVshT+eEHCpJ2DdpALoO0z4sw==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
