---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    password: AgAoIPSySeydJ02crSG/Imp66VHDuY9XnWSDQ58HXZFOGL5S4X2X2aRezGIP+4TAJ5AFqRzYrkSFcTQ+Md6ElcBL6p6rOOhp8cpZqRiGQ6MSx38jyM9Y+v+J+9DhJnsyRj8XVNNyBkH9Jn2Fst/RgmIlL6gqi61Pajb64SvU5zeQ14IB84ZLgsu18KnSHhSs05mTVbcZ5IDfOQCB0m2zcmahGu/dKdX/74AQE/x4cgw0Uins4f/fEuXS2JLo8bKlnPcOl5s7LXM9tL8MOWxLxyl2cA9qNh4m6gj2vQe7P/vmZ4p15q38YVlclWsrJRkxIQH9iXxjxohvWkHslZkBseqJSRAhlphNMxZS2lMLSHj8f6Gux4Mhy52pIy4FXiQUI5yWLpAJCIqK5FQvCRhmVUeHzbBlqLK6qFcepI6NaPk32MAr40AvrVYRtcEAFDquCW6KtXX2lNzCDWm55bw61LLao2TIkboppLRaphQEKpMiHsx5U9YnR4B5iLRNpZhdUKosoNvHMS+fbw/5UWoU6nFYTjHpOhF9INcJTHlqBkpDxYEnkrpxwVt5gqlhm1jESv6w4Ixuo6pRQXf52T24VzYO+EsTiW/2RiW4qenNOD+ggX+sJlqfGNKA5q5TYrbckngwEpp0zY+bHrEdLubzBlk5BGdPkkVXxnjKIIT5NT3dqLncCYz7eYFdudEGlZgx/nxQvrsWtf6buA9jRY/dDou//Xa4U6fNF1BO7Zm2vcVesEkyVMnGeB8=
    user: AgDAnUrnwqZCAi/ZLllqypak2tJyS3Hc+Y0dqvgM+vmtZeGapOC+G6PTVT8u/lN25PrUtmqwbYVHfqDf93nqNrMB65jQU98pSCuWqnNB9I/IU+x5ivcePbBk5SaD1FAeSWdkpHJj8DDWZm6baFGgiJOKMrrOaOKYG1KhFdQScLH/EfsezJoeikwntBzNh1NTySJKNU5pt9z7PTrYkzXNWaWyo5w6ipxhRoJMyKq82tf64Crz/u83yori0r0ReOBw+sHORb0NZBMHwBBDklUFUUO58BzY8DUW+z6zvE2GMNAVqRc8ebF6N74f4wdt0u1A2IjmjkdZ+2JzCrXprtZNtvT1oFmZKavEZITpV6EsVSuL8qAYAjkafh7hS+ltkr4wMdiiNNtjEriZs+QkGx9tCNX87lOOleW0ne+rGCFd4wv8ZGcHnhStFv7EJLUZAz5aKBxNcAghuR610blzT3Gwdk3Het25KhyZsfDrfT7GBeRj73PhyhPDkkoC2cDQyU14szq1VMoivUFLZvYbbF9i+zRhDYWUhFqS+Zt6jvmwtOnNIV1YfwPvVdU+RR8TUXfTE19hbei/bL8qijnHPrAQpZ683UlbwAHaKhSQPrHwcZWL9NIBKl7bcoJD84ZyTNsHUYTc6FRlyysbB/RKugIO7mcTwdUztYSCl+3TYBKylXNhGKiZMKxEK3GUODHprN0gbmzzy5wbsA==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
