---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: monitoring-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgDILI0fl0R9qQlWp/rnyYO0en4Ab8+d0zsrzP2CTW8SMdxsChV+Bgk6bIoPFF9cbiKPmpJ/W6pZJ9M/N1Z/xq+TqNeT7ySo395VWIv/untICPI3m98123IqPmukzhkKAKtitkKeQtyHe72fV+a5/P7/OcB5xi5tqbqRa1tRP5oHjTEHZPSrrE3yUUJts9l8uZua7YiPepcU+OULhYGWDyuGl+8z8DudDnp3F5ejlE2NHfxe0dBJh3UebzRqtmJrJCHKi05rFJzcJqmxkFyb20pjny0S/47vkyEpO+wU3wFBLTcytlzMt0MMIDbsx9VoznpUhsKznyaNorlyyxNtr6Nb7tebJqcFcMVCDBEQwan7/o5E2eQ05uC6isyhC83/RzDttH/kzX5Rue7IcCNpMy/ucTJCxqENEW7vCaAxTZNLB8ROFGgICyhPOyiI6fTv6iXR/HEvP1tzdx1guDQxH9JJ2XGGVWSSgqOE/Q9YleyMZbNiF/s6E+6Z/FmCUebrLuHK4So2VbH4xegLX7lI2kkoGklccIU4bdiVw6YTcFJFTRGroA0P7oBIPfVFeKLUH9wHszoIJFJD9ELmrs6ICwBGuO9S30XBy9zhkTFKcKIpKYYYTYl1/WeIM3oXXnFVcpeSTY2xpc2NsXML6xq/kXme8lJut09qONoy8rvuQplq+qek/qNRIQIrPHa2S6r4X9kj5V318M/2gygoSuDOzPHEHno/Wghk9W2CuZcb3rQqczkajSYHkw==
    admin-user: AgDXOqs9uLp0TBLQErhLiIVxERBF3AC98jWcyDr/K/klF76t8EP40smfgX0IMMsqPQtqVvPOS/PxgTdoCYzigBoJcoWgz63naYrEf0+G4y5lJcqzxEAfi27mPhvrmpw3RPLTdSdtekQ5USQyjwoJNSWl47ML915ZaZ+/iO+HCyDtVu96BbxHKjIrqJjdQ0HfkguEJ8vz6JrYfAS4CS5cICbxc8bX4XR/avfqU+1T+sfdk9E+L7hY98/8JPOXsSA34BVEeHH6xpT/ha/zQeQ7DoqaXGu4TnMkd4V15H7vNuXUFiQ1g/PFhVcC4exQSlfkjukccb2D5FrvRvn/XAl2Npgsbg5A3R9D9vylZW0yCFhB6M4iWNFw/rVsiRJRxjR2/lYiR79xpjF1CjS7MJgnkFDTOhmCfD4gj4bNUL0ana2x5RLD1IKRWCLH00060JtzXAGMIVAPKmMzP17cszEoCpntOohldiqX1I8l4ieXd5r2jqcwmKcm3s1cM67qo3gog9UI1OAdQaTMjoUcrc3OXsBQqOnlNEbfC4oxV9oBcjgEJOcyciTwuKi59qJ4aEEiWUdJU1/GuUfSagwDGJpHcu++P7y3UyBO7fO2UXHbRKedeby976s7FBrGlA4okeT1/kF0B7zg9DQaZF9MwlO5cqn2U4YChgcK1OEIszRFyFm+UiVcDWrls1a6kAhafRew9WE7wfq6tQ==
  template:
    metadata:
      name: monitoring-grafana
      namespace: monitoring
