apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-ingress.yaml
  - grafana-headers-middleware.yaml
  - alerts.yaml
  - grafana-admin-secret.yaml
  - grafana-dashboards.yaml
  - invenio-servicemonitor.yaml
  - networkpolicy-kube-api.yaml
  - alertmanager-discord-secret.yaml
  - alertmanager-discord-deployment.yaml
  - alertmanager-discord-service.yaml
  - alertmanager-discord-netpol.yaml
  - loki-networkpolicy.yaml
