apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-allow-internal
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: loki
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: 3100
          protocol: TCP
    - from:
        - podSelector: {}
      ports:
        - port: 3100
          protocol: TCP
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - port: 53
          protocol: UDP
        - port: 53
          protocol: TCP