apiVersion: v1
kind: ResourceQuota
metadata:
  name: velero-quota
  namespace: velero
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "2"
    limits.memory: "4Gi"
    pods: "10"